# Generated by Django 2.1.7 on 2019-12-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('users', '0002_usercourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCourse',
            new_name='UserFood',
        ),
    ]
