# Generated by Django 2.1.7 on 2019-12-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191226_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='账户金额'),
        ),
    ]
